# .github/workflows/recent-activity.yml
name: Update README with recent activity
on:
  schedule: [{ cron: "0 0 * * *" }]  # daily at 00:00 UTC
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: Readme-Workflows/recent-activity@v2
        with:
          COMMIT_MSG: "chore: update recent activity"
