# .github/workflows/wakatime.yml
name: Update WakaTime stats
on:
  schedule: [{ cron: "0 */12 * * *" }]  # every 12 hours
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-waka:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.3.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: "chore: update WakaTime"
          BLOCKS: "->,->"
          SHOW_TITLE: "true"
          TIME_RANGE: "last_7_days"
          SHOW_TOTAL: "true"
